### ISSUE TITLE
more detailed explanation of view stats

### ISSUE THREAD

**Issue by Ambrosiani** [yonathan06/cassandra-GLAM-tools#11]
hi, it would be really helpful with a detailed explanation of how the view stats are compiled in this tool, compared to Magnus Manske's tools BaGLAMa2 and Glamorgan.

<img width="674" alt="Skärmavbild 2021-11-22 kl  12 07 56" src="https://user-images.githubusercontent.com/2394405/142851072-9f99b2da-e578-4cf5-b99e-8de50a7bb769.png">

As you can see from the graph, the stats differ a bit between the three tools (this is Nordic Museum data). I think (but am not 100 % certain) that some possible variances might be:

* is only the top level category used or are subcategories included and how deep?
* how often is the category checked – i.e. if an image is added or removed to the category when does this impact stats?
* are views checked from the daily wikipedia pageview stats or are they calculated from averages?
* are wikipedia pages with a file displayed in a template (not in the actual page content) counted?
* if multiple images from the set are on the same wikipedia page, are the views of that page counted once or for each image?

current description from each tool:

**Cassandra:**
> This line chart shows the sum of the views for the files thats belong to the main category with a 24h span.
> Generally the difference of visits between workdays and weekends is quite visible. Sometimes some spikes could lead to a popular event. A growing trend is not always equals to a growing popularity of the category because of file additions.
> This statistic is updated every day (max lag time 24h). The data collected here are taken from https://dumps.wikimedia.org/other/mediacounts/daily/. A visit is recorded every time a device download a specific file from a Wikimedia server. So it counts both actual visits, and visits on pages where the file is present (but only if loaded on the device). Actually this is the most precise statistic released by Wikimedia servers.

**BaGLAMa2:**

> BaGLAMa shows you page view numbers for pages on Wikipedia (and other Wikimedia sites) containing Commons files in a specific category. Since February 2014, a new software is used to aggregate page views, so there may be minute differences.
> The new Wikimedia pageview API (human views only, no bots) is used starting 2015-12!

(https://glamtools.toolforge.org/baglama2/)

**Glamorgan:**

> This tool is a variant of baGLAMa2. It can show the view number of pages that include files from a specific Commons category. Human views only, article namespace only. 30K files max in category tree. This tool is run "live", so it may take a while to run.

(https://glamtools.toolforge.org/glamorgan.html)

**Comment by yonathan06** [comment]
hi @NordicMuseum, I'm not familiar with how the different tools work.
I can tell you that in cassandra it takes all of the images from the category, and any sub categories, and checks the daily media view count for each image based on a db dump from wikimedia

As you said, a difference might be due to different images being loaded (from different categories), of a different data source (maybe the other tools do not use the db dump but an API call or a direct read from a db replica)

**Comment by Ambrosiani** [comment]
Hi, does Cassandra check against the category each day? I.e. if an image is in the category on Jan 1 but not on Jan 2, does it only count the views from Jan 1? (This is not possible in a retrospective tool like Glamorgan)

**Comment by yonathan06** [comment]
Cassandra checks each day, if the image is removed from a certain day, it won't have any view counts from that day
