### ISSUE TITLE
Met stats seem to be dead

### ISSUE THREAD

**Issue by fuzheado** [yonathan06/cassandra-GLAM-tools#12]
Can you check to see why this is not working? Thanks. https://glamwikidashboard.org/MET

**Comment by yonathan06** [comment]
@fuzheado hi, sorry for the delay, we disabled MET because we didn't have enough server resources to process it. We are in the progress of moving the dashboard to a new server, and hopefully then we can turn it back on

**Comment by yonathan06** [comment]
@fuzheado we moved to new wmcloud, and restored the MET in the dashboard
https://glamwikidashboard.wmcloud.org/MET
notice there is some gap in data, it will take a couple of days to restore the gap

**Comment by fuzheado** [comment]
> @fuzheado we moved to new wmcloud, and restored the MET in the dashboard https://glamwikidashboard.wmcloud.org/MET notice there is some gap in data, it will take a couple of days to restore the gap

Thanks so much for your help!
