### ISSUE TITLE
README.md and documentation shortcomings

### ISSUE THREAD

**Issue by fuzheado** [yonathan06/cassandra-GLAM-tools#7]
Does the README.md provide enough documentation to install the system from scratch? For example:

"Copy the file config/config.example.json to config/config.json and modify it as required."

This seems like there's a lot that needs to be done here in terms of database setup, and I'm not sure what the right directions would be here. Thanks.

**Comment by yonathan06** [comment]
The documentation is insufficient, it was not modified from the forked repo.
We need to make the documentation better, it is definitely in the todo list

**Comment by yonathan06** [comment]
I added a small update to the readme, right now only the app part is complete, I still need to finalize the services part
